-- TABLES --
-- STOCK
CREATE TABLE STOCK(
	ID BIGINT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	QUANTITY INT NOT NULL
);

-- EXCHANGE
CREATE TABLE EXCHANGE(
	ID BIGINT PRIMARY KEY,
	NAME VARCHAR (50) NOT NULL,
	BALANCE NUMERIC(20, 2),
	CHARGE_AMOUNT NUMERIC(3, 2)
);

-- EXCHANGE
CREATE TABLE STOCK_EXCHANGE(
	STOCK_ID BIGINT,
	EXCHANGE_ID BIGINT,
	foreign key(STOCK_ID) references STOCK(ID),
	foreign key(EXCHANGE_ID) references EXCHANGE(ID),
	primary key(STOCK_ID, EXCHANGE_ID)
);


-- PORTFOLIO
CREATE TABLE PORTFOLIO(
	ID BIGINT PRIMARY KEY,
	INVESTOR_ID BIGINT NOT NULL,
	STOCK_ID BIGINT NOT NULL,
	QUANTITY INT NOT NULL,
	foreign key(INVESTOR_ID) references INVESTOR(ID),
	foreign key(STOCK_ID) references STOCK(ID)
);

-- INVESTOR
CREATE TABLE INVESTOR(
	ID BIGINT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	EXCHANGE_ID BIGINT NOT NULL,
	BALANCE NUMERIC(20, 2),
	foreign key(EXCHANGE_ID) references EXCHANGE(ID)
)

-- TRANSACTION
CREATE TABLE TRANSACTION(
	ID BIGINT PRIMARY KEY,
	EXCHANGE_ID BIGINT NOT NULL,
	INVESTOR_ID BIGINT NOT NULL,
	STOCK_ID BIGINT NOT NULL,
	OPERATION_TYPE CHAR(1) NOT NULL,
	foreign key(EXCHANGE_ID) references EXCHANGE(ID),
	foreign key(INVESTOR_ID) references INVESTOR(ID),
	foreign key(STOCK_ID) references STOCK(ID)	
)

